// <auto-generated />
using System;
using Demo1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo1.Data.Migrations
{
    [DbContext(typeof(AchievementDbContext))]
    [Migration("20260508142732_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Demo1.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerValue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Visit 5 different pages",
                            Icon = "🧭",
                            Name = "Explorer",
                            Target = 5,
                            TriggerType = "PageVisitCount"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Trigger rate limiting",
                            Icon = "⚡",
                            Name = "Speed Demon",
                            Target = 1,
                            TriggerType = "RateLimited"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Find an XSS vector in Security Lab",
                            Icon = "🎩",
                            Name = "White Hat",
                            Target = 1,
                            TriggerType = "SecurityLabXss",
                            TriggerValue = "/SecurityLab/Attack"
                        },
                        new
                        {
                            Id = 4,
                            Description = "View the Performance Dashboard",
                            Icon = "📊",
                            Name = "Benchmarker",
                            Target = 1,
                            TriggerType = "SpecificPage",
                            TriggerValue = "/Performance/Dashboard"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Call any API endpoint",
                            Icon = "🔎",
                            Name = "API Curious",
                            Target = 1,
                            TriggerType = "ApiCall",
                            TriggerValue = "/api/"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Visit every page on the site",
                            Icon = "🏅",
                            Name = "Completionist",
                            Target = 8,
                            TriggerType = "AllPages"
                        });
                });

            modelBuilder.Entity("Demo1.Models.AchievementEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("AchievementEvents");
                });

            modelBuilder.Entity("Demo1.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("Demo1.Models.UserAchievement", b =>
                {
                    b.HasOne("Demo1.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("Demo1.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
